version: "3.9"

services:
  telegram-bot:
    image: python:3.11-alpine
    container_name: telegram_bot
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python save_to_local_bot.py"]
    volumes:
      - ./:/app  # Mount the current directory to /app in the container
    restart: always
