version: "3.9"

services:
  telegram-bot:
    image: telegram-bot:latest  # Use a pre-built image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    working_dir: /app
    command: ["python", "save_to_local_bot.py"]
    volumes:
      - .:/app
    restart: always
