# https://redis.io/docs/getting-started/installation/install-redis-on-windows/
version: '3.9'
services:
  redis:
      image: 'bitnami/redis:latest'
      container_name: redis
      restart: always
      ports:
        - 6379:6379
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - ./redis-persistence:/opt/bitnami/redis/data
        - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf